apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-api
  labels:
    app.kubernetes.io/name: apprise-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "100Mi" .Values.persistence.storageSize }}

