apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-cli-rest-api
  labels:
    app.kubernetes.io/name: signal-cli-rest-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}

